url: https://szetoai.github.io

# Site settings
title: szeto.ai
description: Aidan Szeto's (Northeastern University) Portfolio Site

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/szetoai
  - title: linkedin
    url: https://www.linkedin.com/in/szetoai

# Build settings
markdown: kramdown
permalink: pretty
